version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.24.1
    parallelism: 1
    working_directory: ~/eclimov/mdshop-front
    steps:
      - checkout
      - attach_workspace:
          at: ~/eclimov/mdshop-front
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist

  deploy:
    docker:
      - image: circleci/golang:1.9.6
    parallelism: 1
    working_directory: ~/eclimov/mdshop-front
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/eclimov/mdshop-front
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh -o "StrictHostKeyChecking no" $DEPLOY_USER@$DEPLOY_HOST bash -c "
              cd /root/opt
              git clone https://github.com/eclimov/mdshop-front ; cd /root/opt/mdshop-front
              git reset --hard
              git pull
              docker-compose stop
              docker container prune -f
              docker image prune -f
              docker network prune -f
              docker volume prune -f"
            scp -r dist/ $DEPLOY_USER@$DEPLOY_HOST:/root/opt/mdshop-front/dist

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
